import React, { useEffect, useState } from "react";

const PROVIDER_NAMES = {
  aws: "AWS",
  azure: "Azure",
  digitalocean: "DigitalOcean",
  fastly: "Fastly",
  gcp: "GCP",
  "ibm-power": "IBM Power",
  "ibm-z": "IBM Z (s390x)",
};

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

function money(v, currency = "USD") {
  // Non-ISO units (e.g. "GB" for Fastly bandwidth) are formatted as plain
  // numbers with a unit suffix instead of a currency symbol.
  if (currency && !/^[A-Z]{3}$/.test(currency)) {
    return `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(v ?? 0)} ${currency}`;
  }
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    maximumFractionDigits: 2,
  }).format(v ?? 0);
}

function pct(v) {
  return `${((v ?? 0) * 100).toFixed(1)}%`;
}

// The dashboard JSON is generated by `costctl report` and committed next to the
// built site so GitHub Pages can serve it statically.
function dataUrl() {
  return `${import.meta.env.BASE_URL}dashboard.json`;
}

export default function App() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [monthIdx, setMonthIdx] = useState(-1); // -1 = latest
  const [view, setView] = useState(() =>
    typeof window !== "undefined" && window.location.hash.includes("services") ? "services" : "overview");

  useEffect(() => {
    fetch(dataUrl())
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then(setData)
      .catch((e) => setError(e.message));
  }, []);

  useEffect(() => {
    const onHash = () =>
      setView(window.location.hash.includes("services") ? "services" : "overview");
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
  }, []);

  if (error) return <div className="wrap"><h1>Cloud Spend</h1><p className="err">Could not load dashboard.json: {error}</p></div>;
  if (!data) return <div className="wrap"><h1>Cloud Spend</h1><p>Loading…</p></div>;

  const snaps = data.snapshots?.length ? data.snapshots : [{ label: data.asOf, asOf: data.asOf, providers: data.providers, totals: data.totals }];
  const idx = monthIdx === -1 ? snaps.length - 1 : monthIdx;
  const snap = snaps[idx];
  const providers = snap.providers || [];
  const totals = snap.totals || { alertCount: 0 };
  const daysLeft = providers[0]?.daysRemainingInYear;

  return (
    <div className="wrap">
      <header>
        <div className="hdr-top">
          <h1>Kubernetes Cloud Spend</h1>
          <div className="hdr-controls">
            <nav className="view-nav">
              <a href="#/overview" className={view === "overview" ? "on" : ""}>Overview</a>
              <a href="#/services" className={view === "services" ? "on" : ""}>Top spenders</a>
            </nav>
            <select className="month-select" value={idx}
                    onChange={(e) => setMonthIdx(Number(e.target.value))}
                    aria-label="Select month">
              {snaps.map((s, i) => (
                <option key={s.label} value={i}>
                  {s.label}{i === snaps.length - 1 ? " (latest)" : ""}
                </option>
              ))}
            </select>
          </div>
        </div>
        <p className="sub">
          As of <strong>{snap.asOf}</strong>
          {Number.isFinite(daysLeft) && <> · <strong>{daysLeft} days</strong> left in the year</>}
          {totals.alertCount > 0 && (
            <> · <span className="hdr-alert">{totals.alertCount} budget alert{totals.alertCount > 1 ? "s" : ""}</span></>
          )}
          {" "}· generated {new Date(data.generatedAt).toLocaleString()}
        </p>
      </header>

      {view === "services" ? (
        <TopSpenders providers={providers} />
      ) : (
        <>
          <ComparisonChart providers={providers} />

          <div className="grid">
            {providers.map((p) => (
              <ProviderCard key={p.provider} p={p} />
            ))}
          </div>

          <Methodology />
        </>
      )}
    </div>
  );
}

function ProviderCard({ p }) {
  const c = p.currency || "USD";
  const b = p.budget;
  const partialMonth = (p.daysElapsedInMonth ?? 0) < (p.daysInCurrentMonth ?? 0);
  return (
    <div className="card">
      <div className="card-head">
        <h2>{PROVIDER_NAMES[p.provider] || p.provider}</h2>
        {b?.budgetAlert && <span className="badge">BUDGET ALERT</span>}
      </div>
      <YearChart series={p.series} budget={b?.annualBudget} currency={c} />
      {p.weeklySeries && <WeeklyChart weeks={p.weeklySeries} currency={c} derived={p.weeklyDerived} />}
      <Row label="Last month avg daily spend" value={money(p.lastMonthAvgDaily, c)} />
      <Row
        label={partialMonth ? `This month so far (${p.daysElapsedInMonth}d of ${p.daysInCurrentMonth})` : "Monthly spend"}
        value={money(p.monthlySpend, c)}
      />
      {partialMonth && (
        <Row label="This month projected" value={money(p.monthlyProjected, c)} />
      )}
      <Row label="Yearly based on this month" value={money(p.yearlyBasedOnThisMonth, c)} />
      <Row label="YTD" value={money(p.ytd, c)} />
      <Row label="(burn rate) total on 31 Dec" value={money(p.burnRate31Dec, c)} />
      <Row label="Daily avg over one year" value={money(p.dailyAvgOverOneYear, c)} />
      {b && (
        <>
          <hr />
          <Row label="Annual budget" value={money(b.annualBudget, c)} />
          <Row label="Projected year total" value={money(b.projectedYearTotal, c)} />
          <Row
            label="Budget utilization"
            value={pct(b.budgetUtilization)}
            valueClass={b.budgetAlert ? "danger" : "ok"}
          />
          <Row
            label="Budget lasts (at current burn)"
            value={
              !Number.isFinite(b.daysUntilBudgetExhausted)
                ? "–"
                : b.daysUntilBudgetExhausted <= 0
                  ? "already spent"
                  : `${Math.floor(b.daysUntilBudgetExhausted)} days${b.budgetExhaustedDate ? ` → ${b.budgetExhaustedDate}` : ""}`
            }
            valueClass={
              Number.isFinite(b.daysUntilBudgetExhausted) &&
              (b.daysUntilBudgetExhausted <= 0 || b.daysUntilBudgetExhausted < (p.daysRemainingInYear ?? 0))
                ? "danger"
                : "ok"
            }
          />
        </>
      )}
    </div>
  );
}

function Row({ label, value, valueClass = "" }) {
  return (
    <div className="row">
      <span className="row-label">{label}</span>
      <span className={`row-value ${valueClass}`}>{value}</span>
    </div>
  );
}

// TopSpenders is the "sub-page": one card per provider showing where the money
// goes, broken down by service. The breakdown reconciles exactly with the
// provider's headline YTD / monthly spend (guaranteed server-side in calc.go).
const TOP_N = 8;

function TopSpenders({ providers }) {
  const [metric, setMetric] = useState("ytd"); // "ytd" | "month"
  const list = providers.filter((p) => p.topServices?.length);
  if (list.length === 0) {
    return <section className="card"><p>No service-level data available.</p></section>;
  }
  return (
    <>
      <section className="card compare">
        <div className="card-head">
          <h2>Top spenders per provider</h2>
          <div className="mode-toggle">
            <button className={metric === "ytd" ? "on" : ""} onClick={() => setMetric("ytd")}>YTD</button>
            <button className={metric === "month" ? "on" : ""} onClick={() => setMetric("month")}>This month</button>
          </div>
        </div>
        <p className="sub">
          Where each provider's spend goes, by service. Values sum exactly to the
          provider's {metric === "ytd" ? "YTD" : "month-to-date"} total.
        </p>
      </section>
      <div className="grid">
        {list.map((p) => (
          <ServiceBreakdown key={p.provider} p={p} metric={metric} />
        ))}
      </div>
    </>
  );
}

function ServiceBreakdown({ p, metric }) {
  const currency = p.currency || "USD";
  const rows = (p.topServices || [])
    .map((s) => ({ service: s.service, value: metric === "ytd" ? s.ytd : s.month }))
    .filter((r) => r.value > 0)
    .sort((a, b) => b.value - a.value);

  const total = rows.reduce((a, r) => a + r.value, 0);
  const onlyUnspecified =
    rows.length === 1 && rows[0].service === "(unspecified)";

  // Collapse the long tail into a single "Other" bucket so the bars stay
  // readable while the total still reconciles.
  let shown = rows.slice(0, TOP_N);
  const rest = rows.slice(TOP_N);
  if (rest.length > 0) {
    const otherVal = rest.reduce((a, r) => a + r.value, 0);
    shown = [...shown, { service: `Other (${rest.length})`, value: otherVal, other: true }];
  }
  const max = Math.max(...shown.map((r) => r.value), 1);

  return (
    <div className="card">
      <div className="card-head">
        <h2>{PROVIDER_NAMES[p.provider] || p.provider}</h2>
        <span className="svc-total">{money(total, currency)}</span>
      </div>
      {onlyUnspecified ? (
        <p className="svc-note">
          No service breakdown yet — this provider's next collector run will
          populate per-service detail.
        </p>
      ) : (
        <ul className="svc-list">
          {shown.map((r) => (
            <li key={r.service} className={`svc-row${r.other ? " svc-other" : ""}`}>
              <span className="svc-name" title={r.service}>{r.service}</span>
              <span className="svc-bar-wrap">
                <span className="svc-bar" style={{ width: `${(r.value / max) * 100}%` }} />
              </span>
              <span className="svc-val">{money(r.value, currency)}</span>
              <span className="svc-pct">{total > 0 ? `${((r.value / total) * 100).toFixed(1)}%` : "–"}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// Methodology explains every number on the page. Formulas mirror
// internal/calc/calc.go — keep the two in sync.
function Methodology() {
  return (
    <section className="card method">
      <h2>How the numbers are calculated</h2>
      <dl>
        <dt>Last month avg daily spend</dt>
        <dd><code>previous month total ÷ days in that month</code></dd>

        <dt>This month so far (MTD)</dt>
        <dd>Sum of the current month's booked days. Cloud bills land 1–3 days late, so
        early in a month this is small — that's data lag, not savings.</dd>

        <dt>This month projected</dt>
        <dd><code>current month avg daily × days in month</code>. The daily average
        only divides by days that actually have data.</dd>

        <dt>Yearly based on this month</dt>
        <dd><code>this month projected × 12</code> — what a full year would cost if
        every month looked like this one.</dd>

        <dt>YTD</dt>
        <dd>Sum of everything booked since Jan 1. Budgets reset on Jan 1.</dd>

        <dt>Burn rate / total on 31 Dec &amp; forecast months (hatched bars, dashed line)</dt>
        <dd>Everything forecast uses one number: the <strong>YTD daily run rate</strong>{" "}
        <code>= YTD ÷ days elapsed this year</code>. Future months are{" "}
        <code>run rate × days in month</code>, the rest of the current month is{" "}
        <code>run rate × remaining days</code>, and 31 Dec ={" "}
        <code>YTD + run rate × days remaining</code>. It is a straight-line
        projection of the whole year so far — one expensive month moves it only
        gradually, which is why forecast bars can differ from last month's actuals.</dd>

        <dt>Budget utilization</dt>
        <dd><code>projected 31 Dec total ÷ annual budget</code>. The alert fires at
        ≥ 90%. Dotted red line in the charts = annual budget.</dd>

        <dt>Budget lasts (at current burn)</dt>
        <dd><code>(annual budget − YTD) ÷ YTD daily run rate</code> → days until the
        money runs out, and the projected "day zero" date. Red when that lands
        before 31 Dec.</dd>

        <dt>Weekly chart (yellow)</dt>
        <dd>Sat–Fri weekly totals. GCP, AWS and Fastly have real daily data.
        DigitalOcean and IBM bill one invoice per month, so their daily values
        are <strong>derived</strong>: <code>monthly invoice ÷ days in month</code>,
        spread evenly (same approach as the old Excel) — the line is therefore
        flat within each month and steps at month boundaries.</dd>

        <dt>Top spenders (sub-page)</dt>
        <dd>Per-provider breakdown of spend by service (YTD or month-to-date).
        The bars sum <strong>exactly</strong> to each provider's headline total —
        the same records that make up YTD, just grouped by service. Azure carries
        full service detail; AWS and GCP populate once their collectors re-run
        with the per-service query; providers billed as a single monthly invoice
        (DigitalOcean, IBM) have no service split.</dd>

        <dt>Comparison chart (top)</dt>
        <dd>Default view shows <code>cumulative spend ÷ annual budget</code> in %
        — this makes big ($3M) and small ($17K) providers comparable and shows
        who is burning budget fastest; crossing the 100% line before December
        means overspend. Fastly's GB cap fits here too, since percentages are
        unitless. Toggle to USD for absolute cumulative spend (linear or log).</dd>

        <dt>Fastly</dt>
        <dd>Invoices are $0 under the committed contract, so we track{" "}
        <strong>bandwidth in GB</strong> instead; the "budget" is the contracted
        10 PB/month (120M GB/year).</dd>
      </dl>
    </section>
  );
}

// YearChart renders the month-by-month progression as an inline SVG:
// bars = monthly spend (hatched when forecast), solid line = cumulative actual,
// dashed line = forecast continuation, red dashed = annual budget.
function YearChart({ series, budget, currency }) {
  if (!series || series.length === 0) return null;

  const W = 320, H = 120, PAD = 6, GAP = 4;
  const nSlots = 12;
  const barW = (W - 2 * PAD - GAP * (nSlots - 1)) / nSlots;

  const maxMonthly = Math.max(...series.map((s) => s.monthly), 1);
  const lastCum = series[series.length - 1].cumulative;
  const maxCum = Math.max(lastCum, budget || 0, 1);

  const x = (i) => PAD + i * (barW + GAP);
  const yBar = (v) => H - PAD - (v / maxMonthly) * (H - 2 * PAD) * 0.9;
  const yCum = (v) => H - PAD - (v / maxCum) * (H - 2 * PAD) * 0.9;

  const pt = (s, i) => `${(x(i) + barW / 2).toFixed(1)},${yCum(s.cumulative).toFixed(1)}`;
  const firstForecast = series.findIndex((s) => s.forecast);
  const actual = firstForecast === -1 ? series : series.slice(0, firstForecast + 1); // include join point
  const forecast = firstForecast === -1 ? [] : series.slice(firstForecast >= 1 ? firstForecast - 1 : 0);

  const actualPts = actual.map((s) => pt(s, series.indexOf(s))).join(" ");
  const forecastPts = forecast.map((s) => pt(s, series.indexOf(s))).join(" ");

  const compact = (v) =>
    new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(v);

  return (
    <div className="chart">
      <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" role="img"
           aria-label="Monthly spend, cumulative YTD and year-end forecast">
        {budget > 0 && (
          <line x1={PAD} x2={W - PAD} y1={yCum(budget)} y2={yCum(budget)}
                className="chart-budget" strokeDasharray="4 3" />
        )}
        {series.map((s, i) => (
          <rect key={s.month} x={x(i)} y={yBar(s.monthly)} width={barW}
                height={Math.max(H - PAD - yBar(s.monthly), 0)}
                className={s.forecast ? "chart-bar chart-bar-forecast" : "chart-bar"}>
            <title>{`${MONTHS[s.month - 1]}${s.forecast ? " (forecast)" : ""}: ${money(s.monthly, currency)} (cum ${money(s.cumulative, currency)})`}</title>
          </rect>
        ))}
        <polyline points={actualPts} className="chart-line" fill="none" />
        {forecastPts && (
          <polyline points={forecastPts} className="chart-line chart-line-forecast"
                    strokeDasharray="5 4" fill="none" />
        )}
      </svg>
      <div className="chart-legend">
        <span><i className="sw sw-bar" /> monthly</span>
        <span><i className="sw sw-line" /> cumulative</span>
        <span><i className="sw sw-forecast" /> forecast → {compact(lastCum)} {currency}</span>
        {budget > 0 && <span><i className="sw sw-budget" /> budget ({compact(budget)})</span>}
      </div>
      <div className="chart-months">
        {Array.from({ length: nSlots }, (_, i) => (
          <span key={i} className={series[i]?.forecast ? "dim" : ""}>{MONTHS[i][0]}</span>
        ))}
      </div>
    </div>
  );
}

// WeeklyChart is a compact Sat–Fri weekly spend line (like the sheet's weekly
// tab), only shown for providers with daily-granular data.
function WeeklyChart({ weeks, currency, derived }) {
  if (!weeks || weeks.length < 2) return null;
  const W = 320, H = 48, PAD = 4;
  const max = Math.max(...weeks.map((w) => w.weekly), 1);
  const x = (i) => PAD + (i / (weeks.length - 1)) * (W - 2 * PAD);
  const y = (v) => H - PAD - (v / max) * (H - 2 * PAD);
  const pts = weeks.map((w, i) => `${x(i).toFixed(1)},${y(w.weekly).toFixed(1)}`).join(" ");
  const avg = weeks.reduce((a, w) => a + w.weekly, 0) / weeks.length;
  const compact = (v) =>
    new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(v);
  return (
    <div className="chart chart-weekly">
      <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" role="img" aria-label="Weekly spend">
        <line x1={PAD} x2={W - PAD} y1={y(avg)} y2={y(avg)} className="chart-avg" strokeDasharray="2 3" />
        <polyline points={pts} className="chart-line-weekly" fill="none" />
        {weeks.map((w, i) => (
          <circle key={w.weekEnd} cx={x(i)} cy={y(w.weekly)} r="2.4" className="chart-dot">
            <title>{`Week ending ${w.weekEnd}: ${money(w.weekly, currency)}`}</title>
          </circle>
        ))}
      </svg>
      <div className="chart-legend">
        <span>
          weekly (Sat–Fri{derived ? ", derived from monthly invoice" : ""}) · avg {compact(avg)} {currency}/wk · {weeks.length} wks
        </span>
      </div>
    </div>
  );
}

// ComparisonChart overlays every provider's cumulative trajectory in one graph.
// Default mode normalizes to "% of annual budget" so small and large providers
// are comparable (and Fastly's GB budget fits too — percentages are unitless);
// the USD mode shows absolute cumulative spend for dollar providers.
const COMPARE_COLORS = ["#4c8dff", "#7ee08a", "#f6c445", "#e07ee0", "#45d4f6", "#ff7e6b"];

function ComparisonChart({ providers }) {
  const [mode, setMode] = useState("budget"); // "budget" | "usd"
  const [scale, setScale] = useState("log"); // "linear" | "log" — USD mode only

  const list =
    mode === "budget"
      ? providers.filter((p) => p.budget?.annualBudget > 0 && p.series?.length)
      : providers.filter((p) => (p.currency || "USD") === "USD" && p.series?.length);
  if (list.length < 2) return null;

  const W = 960, H = 220, PAD = 10;
  const val = (p, s) =>
    mode === "budget" ? (s.cumulative / p.budget.annualBudget) * 100 : s.cumulative;

  // Log scale only applies to the absolute-USD view. With ~3 orders of magnitude
  // between GCP (~$3M) and DigitalOcean (~$4.5K), a linear axis flattens the
  // small providers onto the baseline; log keeps them all readable.
  const logScale = mode === "usd" && scale === "log";

  const maxVal =
    mode === "budget"
      ? Math.max(...list.flatMap((p) => p.series.map((s) => val(p, s))), 110)
      : Math.max(...list.flatMap((p) => p.series.map((s) => s.cumulative)), 1);

  // Log domain: smallest positive cumulative rounded down to a power of ten, up
  // to the max rounded up — so the axis spans whole decades.
  const positives = list.flatMap((p) => p.series.map((s) => s.cumulative)).filter((v) => v > 0);
  const logMin = Math.pow(10, Math.floor(Math.log10(Math.min(...positives, maxVal))));
  const logMax = Math.pow(10, Math.ceil(Math.log10(maxVal)));

  const x = (i) => PAD + (i / 11) * (W - 2 * PAD);
  const y = (v) => {
    if (logScale) {
      const c = Math.max(v, logMin); // clamp near-zero/early months to the floor
      const t = (Math.log10(c) - Math.log10(logMin)) / (Math.log10(logMax) - Math.log10(logMin));
      return H - PAD - t * (H - 2 * PAD);
    }
    return H - PAD - (v / maxVal) * (H - 2 * PAD);
  };

  const compact = (v) =>
    new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(v);

  // Grid lines: budget-% thresholds in budget mode, powers of ten in USD-log,
  // none in USD-linear.
  let gridLines = [];
  if (mode === "budget") {
    gridLines = [25, 50, 75, 90, 100];
  } else if (logScale) {
    for (let e = Math.log10(logMin); e <= Math.log10(logMax) + 1e-9; e++) {
      gridLines.push(Math.pow(10, Math.round(e)));
    }
  }
  const gridLabel = (g) => (mode === "budget" ? `${g}%` : `$${compact(g)}`);
  const gridDanger = (g) => mode === "budget" && g >= 90;

  return (
    <section className="card compare">
      <div className="card-head">
        <h2>{mode === "budget" ? "Budget utilization — all providers" : `Cumulative spend — USD providers${logScale ? " (log)" : ""}`}</h2>
        <div className="mode-toggle">
          <button className={mode === "budget" ? "on" : ""} onClick={() => setMode("budget")}>% of budget</button>
          <button className={mode === "usd" ? "on" : ""} onClick={() => setMode("usd")}>USD</button>
          {mode === "usd" && (
            <>
              <span className="toggle-sep" aria-hidden="true" />
              <button className={scale === "linear" ? "on" : ""} onClick={() => setScale("linear")}>linear</button>
              <button className={scale === "log" ? "on" : ""} onClick={() => setScale("log")}>log</button>
            </>
          )}
        </div>
      </div>
      <div className="chart">
        <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" role="img"
             aria-label="Cumulative comparison across providers">
          {gridLines.map((g) => (
            <g key={g}>
              <line x1={PAD} x2={W - PAD} y1={y(g)} y2={y(g)}
                    stroke={gridDanger(g) ? "var(--danger)" : "var(--line)"}
                    strokeWidth={g === 100 && mode === "budget" ? 1.4 : 0.7}
                    strokeDasharray={gridDanger(g) ? "5 4" : "2 5"}
                    opacity={gridDanger(g) ? 0.75 : 0.6} />
              <text x={W - PAD - 2} y={y(g) - 3} textAnchor="end" className="grid-label">{gridLabel(g)}</text>
            </g>
          ))}
          {list.map((p, pi) => {
            const color = COMPARE_COLORS[pi % COMPARE_COLORS.length];
            const firstF = p.series.findIndex((s) => s.forecast);
            const actual = firstF === -1 ? p.series : p.series.slice(0, firstF + 1);
            const forecast = firstF === -1 ? [] : p.series.slice(Math.max(firstF - 1, 0));
            const toPts = (arr) =>
              arr.map((s) => `${x(s.month - 1).toFixed(1)},${y(val(p, s)).toFixed(1)}`).join(" ");
            return (
              <g key={p.provider} stroke={color}>
                <polyline points={toPts(actual)} fill="none" strokeWidth="2.2" />
                {forecast.length > 0 && (
                  <polyline points={toPts(forecast)} fill="none" strokeWidth="1.8" strokeDasharray="6 4" opacity="0.7" />
                )}
                {mode === "usd" && p.budget?.annualBudget > 0 && (
                  <line x1={PAD} x2={W - PAD} y1={y(p.budget.annualBudget)} y2={y(p.budget.annualBudget)}
                        strokeWidth="1" strokeDasharray="2 4" opacity="0.5" />
                )}
              </g>
            );
          })}
        </svg>
        <div className="chart-legend">
          {list.map((p, pi) => {
            const last = p.series[p.series.length - 1];
            const lbl =
              mode === "budget"
                ? `${Math.round(val(p, last))}% by Dec`
                : compact(last.cumulative);
            return (
              <span key={p.provider}>
                <i className="sw" style={{ background: COMPARE_COLORS[pi % COMPARE_COLORS.length] }} />
                {PROVIDER_NAMES[p.provider] || p.provider} ({lbl})
              </span>
            );
          })}
          <span className="dim-note">
            solid = actual · dashed = forecast{mode === "budget"
              ? " · red lines = 90% alert / 100% budget"
              : logScale
                ? " · log scale (powers of ten) · dotted = budget"
                : " · dotted = budget"}
          </span>
        </div>
        <div className="chart-months chart-months-wide">
          {MONTHS.map((mn) => <span key={mn}>{mn}</span>)}
        </div>
      </div>
    </section>
  );
}

